// External Imports
import { Toaster } from "sonner";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Fira_Code } from "next/font/google";

// Local Imports
import Providers from "./providers";

// Styles
import "@/styles/globals.css";

const plusJakarta = Plus_Jakarta_Sans({
    variable: "--font-sans",
    subsets: ["latin"],
    display: "swap",
    weight: ["400", "500", "600", "700", "800"],
});

const firaCode = Fira_Code({
    variable: "--font-mono",
    subsets: ["latin"],
    display: "swap",
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${plusJakarta.variable} ${firaCode.variable} font-sans antialiased h-screen`}
                suppressHydrationWarning
            >
                <Providers>
                    {children}
                    <Toaster />
                </Providers>
            </body>
        </html>
    );
}
